const { test, expect } = require('@playwright/test');

test('POST Create User', async ({ request }) => {
    const response = await request.post('https://jsonplaceholder.typicode.com/posts', {
        data: {
            title: 'Playwright API',
            body: 'Generated by API Framework Generator Skill',
            userId: 1
        }
    });

    expect(response.status()).toBe(201);

    const body = await response.json();

    expect(body.title).toBe('Playwright API');
});